main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        '',
        views.QuestionnaireList.as_view(),
        name='index'
    ),
    path(
        'questions/<topic>/process_answer',
        views.ProcessAnswer.as_view(),
        name='process_answer'
    ),
    path(
        'questions/<topic>',
        views.QuestionsList.as_view(),
        name='questions'
    ),
    path(
        'results/<user>',
        views.ResultsList.as_view(),
        name='results'
    ),
    path(
        'results/<user>/<id>',
        views.ResultView.as_view(),
        name='result'
    ),
    path(
        'questionnaire_editor',
        views.QuestionnaireEditor.as_view(),
        name='add_questionnaire'
    ),
    path(
        'questionnaire_editor/add_questionnaire',
        views.ProcessNewQuestionnaire.as_view(),
        name='process_questionnaire'
    ),
    path(
        'questionnaire_editor/get_questions',
        views.GetQuestionnaireQuestions.as_view(),
        name='get_questions'
    ),
    path(
        'questionnaire_editor/add_existing_question',
        views.GetQuestionVariants.as_view(),
        name='add_existing_question'
    ),
]

questionnaire/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from . import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('main.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.contrib.auth.models import User
from smart_selects.db_fields import ChainedForeignKey
from django.core.exceptions import ValidationError


class Questionnaire(models.Model):
    """ Модель опросника."""
    questionnaire = models.CharField(
        max_length=50,
        unique=True,
        verbose_name='Название вопросника'
    )

    def __str__(self):
        return self.questionnaire

    class Meta:
        verbose_name = "Вопросник"
        verbose_name_plural = "Вопросники"


class Question(models.Model):
    """ Модель вопроса."""
    questionnaire = models.ForeignKey(
        Questionnaire,
        on_delete=models.CASCADE,
        verbose_name='Название вопросника'
    )
    question_num = models.PositiveIntegerField(
        verbose_name='Номер вопроса в вопроснике'
    )
    question = models.CharField(
        max_length=200
        , verbose_name='Вопрос'
    )
    question_type = models.IntegerField(
        choices=(
            (1, 'Вопрос без вариантов ответа'),
            (2, 'Вопрос с одним вариантом ответа'),
            (3, 'Вопрос с несколькими вариантами ответа')
        ),
        default=2,
        verbose_name='Тип вопрос'
    )

    def __str__(self):
        return '({}) Вопрос {}: {}'.format(
            self.questionnaire,
            self.question_num,
            self.question
        )

    class Meta:
        verbose_name = "Вопрос"
        verbose_name_plural = "Вопросы"
        unique_together = ('questionnaire', 'question_num',)


class Variant(models.Model):
    """ Модель варианта ответа на вопрос."""
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        verbose_name='Вопрос'
    )
    variant = models.CharField(
        max_length=200,
        verbose_name='Вариант ответа'
    )

    def __str__(self):
        return 'Вариант ответа: "{}" на вопрос "{}"'.format(
            self.variant,
            self.question
        )

    class Meta:
        verbose_name = "Вариант ответа"
        verbose_name_plural = "Варианты ответа"


class RightVariant(models.Model):
    """ Модель правильного варианта ответа на вопрос."""
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        verbose_name='Вопрос'
    )
    variant = ChainedForeignKey(
        Variant,
        chained_field="question",
        chained_model_field="question",
        show_all=False,
        auto_choose=True,
        sort=True,
        verbose_name='Вариант ответа'
    )

    def __str__(self):
        return 'Правильный ответ: "{}" на вопрос "{}"'.format(
            self.variant.variant,
            self.question
        )

    def save(self, *args, **kwargs):
        question_type, question_ids = self.get_is_vaild_info()
        if question_type == 1 or question_type == 2:
            if self.question.id in question_ids:
                raise ValidationError(
                    'Для этого вопроса уже выбран правильный вариант ответа!'
                )
            else:
                super(RightVariant, self).save(*args, **kwargs)
        else:
            super(RightVariant, self).save(*args, **kwargs)

    def clean(self):
        question_type, question_ids = self.get_is_vaild_info()
        if question_type == 1 or question_type == 2:
            if self.question.id in question_ids:
                raise ValidationError(
                    'Для этого вопроса уже выбран правильный вариант ответа!'
                )

    def get_is_vaild_info(self):
        question_type = Question.objects.get(
            questionnaire=self.question.questionnaire,
            question=self.question.question
        ).question_type
        all_right_variants = RightVariant.objects.all()
        question_ids = []
        for right_variant in all_right_variants:
            question_id = right_variant.question_id
            if question_id not in question_ids:
                question_ids.append(question_id)
        return question_type, question_ids

    class Meta:
        verbose_name = "Правильный ответ"
        verbose_name_plural = "Правильные ответы"


class Results(models.Model):
    """ Модель хренения результатов."""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Пользователя'
    )
    questionnaire = models.ForeignKey(
        Questionnaire,
        on_delete=models.CASCADE,
        verbose_name='Вопросника'
    )
    date = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата и время прохорждения тестирования'
    )
    result = JSONField(
        verbose_name='Результат'
    )
    percent_result = models.IntegerField(
        verbose_name='Процент правильных ответов'
    )

    class Meta:
        verbose_name = "Результат"
        verbose_name_plural = "Результаты"

main/views.py
import json
from collections import defaultdict

from django.views.generic import ListView, View
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import reverse
from main.models import *


QUESTION_TYPES = {
    'Вопрос без вариантов ответа': 1,
    'Вопрос с одним вариантом ответа': 2,
    'Вопрос с несколькими вариантами ответа': 3
}


class QuestionnaireList(ListView):
    """ View главной страницы."""
    model = Questionnaire
    template_name = 'main/home_page.html'


class QuestionsList(QuestionnaireList):
    """ View страницы опросника."""
    template_name = 'main/questions.html'

    def get_context_data(self, **kwargs):
        topic = self.kwargs['topic']
        context = super(QuestionsList, self).get_context_data(**kwargs)
        questions_with_variants = defaultdict(list)
        questions = Question.objects.filter(
            questionnaire__questionnaire=topic).order_by('question_num')
        variants = Variant.objects.filter(
            question__questionnaire__questionnaire=topic
        ).order_by('question__question_num')

        # Компоновка опросника для передачи в context.
        for question in questions:
            if question.question_type == 1:
                questions_with_variants[(
                    ('{}. {}'.format(
                        question.question_num, question.question)),
                    question.question_type,
                    question.questionnaire.questionnaire,
                    question.id
                )] = []
            else:
                for variant in variants:
                    if question.id == variant.question_id:
                        questions_with_variants[(
                            ('{}. {}'.format(
                                question.question_num,
                                question.question
                            )),
                            question.question_type,
                            question.questionnaire.questionnaire,
                            question.id
                        )].append(variant.variant)

        questions_with_variants.default_factory = None
        context['questions_with_variants'] = questions_with_variants
        return context


class ProcessAnswer(View):
    """ View для обработки ответа на вопросник."""
    def post(self, request, **kwargs):
        topic = self.kwargs['topic']
        res_form = json.loads(request.body.decode('utf-8'))
        res_form.pop('csrfmiddlewaretoken')

        questions = Question.objects.filter(
            questionnaire__questionnaire=topic).order_by('question_num')
        right_variants = RightVariant.objects.filter(
            question__questionnaire__questionnaire=topic
        ).order_by('question__question_num')

        # Компоновка правильных ответов для последующего
        # сравнения с ответами пользователя.
        questions_with_right_variants = {}
        for question in questions:
            if question.question_type == 3:
                questions_with_right_variants[question.question_num] = []
                for right_variant in right_variants:
                    if (question.question_num ==
                            right_variant.question.question_num):
                        questions_with_right_variants[
                            question.question_num
                        ].append(right_variant.variant.variant)
            else:
                for right_variant in right_variants:
                    if (question.question_num ==
                            right_variant.question.question_num):
                        questions_with_right_variants[
                            question.question_num
                        ] = right_variant.variant.variant

        # Компоновка правильных ответов и ответов пользователя в один объект.
        qusetionnaire_res = {}
        for question_res in res_form:
            qusetionnaire_res[int(question_res)] = [
                res_form[question_res],
                questions_with_right_variants[int(question_res)]
            ]

        # Сравнение ответов пользовтаеля с правильными ответами.
        right_answers_num = 0
        for question_res in qusetionnaire_res:
            if isinstance(qusetionnaire_res[question_res][1], str):
                qusetionnaire_res[
                    question_res][0] = qusetionnaire_res[question_res][0][0]
                if (qusetionnaire_res[question_res][0].lower().strip() ==
                        qusetionnaire_res[question_res][1].lower()):
                    qusetionnaire_res[question_res].append(1)
                    right_answers_num += 1
                else:
                    qusetionnaire_res[question_res].append(0)
            else:
                if (list(set(qusetionnaire_res[question_res][0]) ^
                             set(qusetionnaire_res[question_res][1]))):
                    qusetionnaire_res[question_res].append(0)
                else:
                    qusetionnaire_res[question_res].append(1)
                    right_answers_num += 1

        # Подсчёт процента правильных ответов.
        percent_result = int(right_answers_num/len(qusetionnaire_res) * 100)

        # Запись результата.
        result = Results(
            user=request.user,
            questionnaire=Questionnaire.objects.get(questionnaire=topic),
            result=json.dumps(qusetionnaire_res),
            percent_result=percent_result
        )
        result.save()

        return HttpResponseRedirect(
            reverse(
                'result',
                kwargs={'user': result.user.username, 'id': result.pk}
            )
        )


class ResultsList(QuestionnaireList):
    """ View страницы с реузльтатами."""
    template_name = 'main/results.html'

    def get_context_data(self, **kwargs):
        context = super(ResultsList, self).get_context_data(**kwargs)
        if self.kwargs['user'] == 'superuser':
            context['results'] = Results.objects.all().order_by('-date')
        else:
            context['results'] = Results.objects.filter(
                user=self.request.user).order_by('-date')
        return context


class ResultView(QuestionnaireList):
    """ View страницы результата."""
    template_name = 'main/result.html'

    def get_context_data(self, **kwargs):
        context = super(ResultView, self).get_context_data(**kwargs)
        context['result'] = Results.objects.get(id=self.kwargs['id'])
        context['result'].result = json.loads(context['result'].result)
        for key, value in context['result'].result.items():
            value.append(
                Question.objects.get(
                    questionnaire=context['result'].questionnaire,
                    question_num=key
                ).question
            )
        return context


class QuestionnaireEditor(ListView):
    """ View редактора для создания опросника."""
    model = Questionnaire
    template_name = 'main/questionnaire_editor.html'


class ProcessNewQuestionnaire(View):
    """ View для обработки и добавления нового опросника."""
    def post(self, request):
        json_questionnaire = json.loads(request.body.decode('utf-8'))

        # Создание нового опросника.
        new_questionnaire = Questionnaire(
            questionnaire=json_questionnaire['questionnaire'])
        new_questionnaire.save()

        for question in json_questionnaire['questions']:
            # Создание нового вопроса.
            new_question = Question(
                questionnaire=new_questionnaire,
                question_num=question['question_num'],
                question=question['question'],
                question_type=QUESTION_TYPES[question['question_type']]
            )
            new_question.save()

            for variant in question['variants']:
                # Создание нового варианта.
                new_variant = Variant(
                    question=new_question,
                    variant=variant['variant']
                )
                new_variant.save()

                if variant['is_right_variant']:
                    # Создание нового правильного варианта.
                    new_right_variant = RightVariant(
                        question=new_question,
                        variant=new_variant
                    )
                    new_right_variant.save()

        return HttpResponse("Опросник успешно добавлен.")


class GetQuestionnaireQuestions(View):
    """
    View для получения вопросов из определённого опросника,
    чтобы вернуть их на страницу редактора для добавления
    уже существующего вопроса.
    """
    def post(self, request):
        questions = Question.objects.filter(
            questionnaire__questionnaire=request.body.decode('utf-8')
        ).order_by('question_num')
        questions_dict = {}
        for question in questions:
            questions_dict[int(question.question_num)] = question.question
        return HttpResponse(json.dumps(questions_dict))


class GetQuestionVariants(View):
    """
    View для получения вариантов ответа на определённый вопрос,
    чтобы вернуть их на страницу редактора для добавления
    уже существующего вопроса.
    """
    def post(self, request):
        requested_question = json.loads(
            request.body.decode('utf-8'))
        question_obj = Question.objects.get(
            questionnaire__questionnaire=requested_question[0],
            question_num=requested_question[1]
        )
        question = question_obj.question
        question_type = question_obj.question_type
        variants = Variant.objects.filter(
            question__questionnaire__questionnaire=requested_question[0],

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load staticfiles %}
    <title>Artezio code questionnaire</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'main/images/favicon.ico' %}"/>
    <link data-require="bootstrap-css@3.1.1" data-semver="3.1.1" rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" />
    <script data-require="jquery@*" data-semver="2.0.3" src="//code.jquery.com/jquery-2.0.3.min.js"></script>
    <script data-require="bootstrap@3.1.1" data-semver="3.1.1" src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'main/js/base.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/footer.css' %}">
    {% block extra_head %}
    {% endblock %}
</head>
<body>
    {% include "main/includes/header.html" %}
    <div id="wrapper">
        {% include "main/includes/navbar.html" %}
        <div class="container content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    {% include "main/includes/footer.html" %}
</body>
</html>

main/templates/main/questionnaire_editor.html
{% extends "main/base.html" %}

{% load staticfiles %}

{% block extra_head %}
    <meta charset="utf-8" />
    <title>Добавление опросника</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'main/images/favicon.ico' %}"/>
    <link rel='stylesheet' href='//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css'>
    <link rel='stylesheet' href='//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css'>
    <script src="{% static 'main/js/jsoneditor.js' %}"></script>
    <style>
        [data-schemapath="root.questions"] table {
            display: block;
            overflow-x: auto;
        }
    </style>
    <script>
    JSONEditor.defaults.theme = 'bootstrap3';
    JSONEditor.defaults.iconlib = 'fontawesome4';
    JSONEditor.defaults.options.object_layout = 'grid';
    JSONEditor.defaults.options.disable_properties = true;
    JSONEditor.defaults.options.disable_collapse = true;
    </script>
{% endblock %}

{% block content %}
    <div class="container" id="error_unique_question"></div>
    <div class="container" id="error_unique_variant"></div>
    <div id='editor_holder'></div>
    <div class="container text-center">
        <button id='submit' class='btn btn-primary btn-lg' disabled>Добавить опросник</button>
    </div>
    <script>
        // Initialize the editor
        var editor = new JSONEditor(document.getElementById('editor_holder'),{
            ajax: true,
            schema: {
              $ref: "{% static 'main/js/questionnaire_schema.json' %}",
            }
        });
		
        $(function() {
            setTimeout(function() {
                $('button[title="Добавить Вопрос"]').after(
                    '<button id="toogle_existing_question" type="button" title="Добавить Существующий Вопрос" class="btn btn-default json-editor-btn-add"><i class="fa fa-plus"></i> Существующий Вопрос</button>\
                    <div id="existing_question_div" style="background-color: white; border: 1px solid black; box-shadow: black 3px 3px; position: absolute; z-index: 10; left: 0px; top: 33px; display: none;">\
                        <select id="questionnaire_selector"><option>---</option>{% for item in questionnaire_list %}<option>{{ item }}</option>{% endfor %}</select><br>\
                        <select id="question_selector"></select><br>\
                        <button id="add_existing_question" type="button" title="Добавить" class="btn btn-default json-editor-btn-save "><i class="fa fa-plus"></i> Добваить</button>\
                    </div>'
                );
                let toogle_flag = true;
                $('#toogle_existing_question').click(function() {
                    if (toogle_flag) {
                        $('#existing_question_div').css("display","block");
                        toogle_flag = !toogle_flag
                    } else {
                        $('#existing_question_div').css("display","none");
                        toogle_flag = !toogle_flag
                    }
                });
                $('#questionnaire_selector').change(function() {
                    $('#question_selector').empty();
                    if ($('#questionnaire_selector').val() != '---') {
                        $.ajax({
                            url: "questionnaire_editor/get_questions",
                            type: "POST",
                            data: $('#questionnaire_selector').val(),
                            success: function(response) {
                                question_obj = JSON.parse(response);
                                for (question_num in question_obj) {
                                    $('#question_selector').append('<option value=' + question_num + '>' + question_num + '. ' + question_obj[question_num] + '</option>');
                                }
                            },
                            error: function(response) {
                                alert("Возникла ошибка при получении вопросов из опросника!");
                            }
                        });
                    }
                });
                $('#add_existing_question').click(function() {
                    $.ajax({
                        url: "questionnaire_editor/add_existing_question",
                        type: "POST",
                        data: JSON.stringify([$('#questionnaire_selector').val(), $('#question_selector').val()]),
                        success: function(response) {
                            response_obj = JSON.parse(response);
                            let type_mapping = {
                                1: 'Вопрос без вариантов ответа',
                                2: 'Вопрос с одним вариантом ответа',
                                3: 'Вопрос с несколькими вариантами ответа'
                            };
                            let json = editor.getValue();
                            json.questions.push(
                                {
                                    "question_num": json.questions[json.questions.length-1].question_num + 1,
                                    "question": response_obj.question,
                                    "question_type": type_mapping[response_obj.question_type],
                                    "variants": []
                                }
                            );
                            response_obj.variants.forEach(function(variant) {
                                let is_right_variant = false;
                                if ($.inArray(variant, response_obj.right_variants) >= 0) {
                                    is_right_variant = true;
                                }
                                json.questions[json.questions.length-1].variants.push({"variant": variant, "is_right_variant": is_right_variant});
                            });
                            editor.setValue(json);
                        },
                        error: function(response) {
                            alert("Возникла ошибка при добавлении вопроса!");
                        }
                    });
                });
            }, 100);
        });

        // Hook up the submit button to send questionnaire to the view
        document.getElementById('submit').addEventListener('click',function() {
            $.ajax({
                url: "questionnaire_editor/add_questionnaire",
                type: "POST",
                data: JSON.stringify(editor.getValue()),
                success: function(response) {
                    location.reload();
                },
                error: function(response) {
                    alert("Извините, возникла ошибка!");
                }
            });
        });

        function unique(arr) {
          var obj = {};
          for (var i = 0; i < arr.length; i++) {
            var str = arr[i];
            obj[str] = true;
          }
          return Object.keys(obj);
        }

        // Validate inputs whenever the editor changes
        editor.on('change',function() {
             // Set question numbers
             let json = editor.getValue()
             for ( i = 0; i < json.questions.length; i++ ) {
                json.questions[i].question_num = i + 1;
             }
             editor.setValue(json);

            // Check if this questionnaire is already available.
            let questionnaire_list = [];
            {% for item in questionnaire_list %}
            questionnaire_list.push('{{ item.questionnaire }}');
            {% endfor %}
            let questionaire_availability_indicator;
            let questionnaire_input_val =  $('input[name="root[questionnaire]"').val();
            if($.inArray(questionnaire_input_val, questionnaire_list) === -1 || questionnaire_input_val.length < 1) {
                $('div[data-schemapath="root.questionnaire"] div:last').empty();
            }
            else {
                $('div[data-schemapath="root.questionnaire"] div:last').html('<p style="color: red;">Опросник с таким именем уже существует.</p>');
                questionaire_availability_indicator = true;
            }

            let checkbox_check_list = []
            let variants_check_list = []
            let type_objs = $('select[name$="[question_type]"]');
            $.each(type_objs, function() {
                let question_index = $(this).attr('name')[$(this).attr('name').search(/[\d]/)];
                let checkboxes = $('input[type="checkbox"][name^="root[questions][' + question_index + '][variants]"');
                $('td[data-schemapath="root.questions.' + question_index + '.variants"] .json-editor-btn-add').css('visibility', 'visible');
   	            if(this.value == "Вопрос с одним вариантом ответа") {
   	                $('td[data-schemapath="root.questions.' + question_index + '.question_type"] div:last').empty();
   	                $('td[data-schemapath="root.questions.' + question_index + '.question_type"] div:last').append('<p class="desc_qtype">Этот тип вопроса должен, обязательно,<br> иметь только один правильный вариант ответ!</p>');
   	                let checked_counter = 0;
   	                $.each(checkboxes, function() {
   	                    if(this.checked == true) {
   	                        checked_counter += 1;
   	                    }
   	                });
   	                if (checked_counter == 1) {
   	                    checkbox_check_list.push(true);
   	                }
   	            }
   	            else if(this.value == "Вопрос без вариантов ответа"){
   	                $('td[data-schemapath="root.questions.' + question_index + '.question_type"] div:last').empty();
   	                $('td[data-schemapath="root.questions.' + question_index + '.question_type"] div:last').append('<p class="desc_qtype">Этот тип вопроса должен, обязательно,<br> иметь правильный вариант ответ!</p>');
   	                $('td[data-schemapath="root.questions.' + question_index + '.variants"] .json-editor-btn-add').css('visibility', 'hidden');
   	                $('td[data-schemapath="root.questions.' + question_index + '.variants"] button[title="Удалить все"]').trigger('click');
   	                let checked_counter = 0;
   	                $.each(checkboxes, function() {
   	                    if(this.checked == true) {
   	                        checked_counter += 1;
   	                    }
   	                });
   	                if (checked_counter == 1) {
   	                    checkbox_check_list.push(true);
   	                }
   	            }
   	            else {
   	                $('td[data-schemapath="root.questions.' + question_index + '.question_type"] div:last').empty();
   	                $('td[data-schemapath="root.questions.' + question_index + '.question_type"] div:last').append('<p class="desc_qtype">Этот тип вопроса должен, обязательно,<br> иметь хотя бы один правильный вариант ответ!</p>');
                    let checked_counter = 0;
   	                $.each(checkboxes, function() {
   	                    if(this.checked == true) {
   	                        checked_counter += 1;
   	                    }
   	                });
                    if (checked_counter > 0) {
   	                    checkbox_check_list.push(true);
   	                }
   	            }
   	            let variant_inputs = $('input[type="text"][name^="root[questions][' + question_index + '][variants]"').map(function() { return $(this).val();}).get();
                if(variant_inputs.length == unique(variant_inputs).length) {
                    variants_check_list.push(true);
                }
            });

            let all_questions = $('input[name$="[question]"]').map(function() { return $(this).val();}).get();
            let questions_number = editor.getValue().questions[editor.getValue().questions.length-1].question_num;

            if(all_questions.length != unique(all_questions).length) {
                $('#error_unique_question').html('<p style="color: red;">Одинаковые вопросы недопустимы.</p>');
            }
            else {
                $('#error_unique_question').empty();
            }

            if(variants_check_list.length != questions_number) {
                $('#error_unique_variant').html('<p style="color: red;">Одинаковые варианты ответов в одном вопросе недопустимы.</p>');
            }
            else {
                $('#error_unique_variant').empty();
            }

            // Get an array of errors from the validator
            var errors = editor.validate();
            // Not valid
            if(
                errors.length ||
                questionaire_availability_indicator ||
                checkbox_check_list.length != questions_number ||
                variants_check_list.length != questions_number ||
                all_questions.length != unique(all_questions).length
            ) {
                $('#submit').attr('disabled', true);
            }
            // Valid
            else {
                $('#submit').attr('disabled', false);
            }
        });
    </script>
{% endblock %}